#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.schemas.scene import build_editor_scene_contract_artifact

ASSET_MANIFEST_PATH = PROJECT_ROOT / "shared" / "catalog" / "editorAssets.json"
SCENE_CONTRACT_JSON_PATH = (
    PROJECT_ROOT / "shared" / "contracts" / "scene" / "editorSceneContract.json"
)
FRONTEND_ASSETS_TS_PATH = (
    PROJECT_ROOT / "frontend" / "src" / "shared" / "generated" / "editorAssets.ts"
)
FRONTEND_SCENE_CONTRACT_TS_PATH = (
    PROJECT_ROOT
    / "frontend"
    / "src"
    / "shared"
    / "generated"
    / "editorSceneContract.ts"
)


def _json_literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, indent=4)


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _normalized(content: str) -> str:
    return content.rstrip() + "\n"


def _check_file(path: Path, expected: str) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    expected_norm = _normalized(expected)
    current_norm = _normalized(current)
    if current_norm == expected_norm:
        return True
    diff = "".join(
        difflib.unified_diff(
            current_norm.splitlines(keepends=True),
            expected_norm.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (expected)",
        ),
    )
    sys.stderr.write(diff)
    return False


def _generate_frontend_assets_ts(asset_manifest: object) -> str:
    literal = _json_literal(asset_manifest)
    return f"""// Generated by `scripts/generate_editor_shared_artifacts.py` from
// `shared/catalog/editorAssets.json`. Do not edit by hand.

export const EDITOR_ASSET_MANIFEST = {literal} as const;

export const EDITOR_ASSET_ORDER = EDITOR_ASSET_MANIFEST.assetOrder;
export const EDITOR_LEGACY_ASSET_ALIASES = EDITOR_ASSET_MANIFEST.legacyAliases;
export const TOOL_FV_ASSET_KEY = EDITOR_ASSET_MANIFEST.toolFvAssetKey;
export const UNKNOWN_DOODAD_VIEW_BOX
    = EDITOR_ASSET_MANIFEST.unknownDoodadFootprint;
export const LINE_FOOTPRINTS = EDITOR_ASSET_MANIFEST.lineFootprints;
export const EDITOR_ASSETS = EDITOR_ASSET_MANIFEST.assets;

export type EditorAssetKey = (typeof EDITOR_ASSET_ORDER)[number];
export type EditorAssetSpec = (typeof EDITOR_ASSETS)[EditorAssetKey];
export type EditorLegacyAssetAlias = keyof typeof EDITOR_LEGACY_ASSET_ALIASES;
"""


def _generate_frontend_scene_contract_ts(scene_contract: object) -> str:
    literal = _json_literal(scene_contract)
    return f"""// Generated by `scripts/generate_editor_shared_artifacts.py` from
// `backend/schemas/scene.py`. Do not edit by hand.

export const EDITOR_SCENE_CONTRACT = {literal} as const;

export const PAINT_LAYER_KINDS = EDITOR_SCENE_CONTRACT.paintLayerKinds;
export const DRAW_STYLES = EDITOR_SCENE_CONTRACT.drawStyles;
export const TOOL_VARIANTS = EDITOR_SCENE_CONTRACT.toolVariants;
export const LEGACY_TOOL_VARIANTS = EDITOR_SCENE_CONTRACT.legacyToolVariants;
export const ACCEPTED_TOOL_VARIANTS = EDITOR_SCENE_CONTRACT.acceptedToolVariants;
export const FILL_MODES = EDITOR_SCENE_CONTRACT.fillModes;
export const FILL_CONNECTIVITY = EDITOR_SCENE_CONTRACT.fillConnectivity;
export const FILL_WALLS_SCOPE = EDITOR_SCENE_CONTRACT.fillWallsScope;
export const SCENE_VERSION = EDITOR_SCENE_CONTRACT.sceneVersion;
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate or verify shared editor artifacts.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are up to date instead of rewriting them.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    asset_manifest = json.loads(ASSET_MANIFEST_PATH.read_text(encoding="utf-8"))
    scene_contract = build_editor_scene_contract_artifact()
    scene_contract_json = _json_literal(scene_contract)
    frontend_assets_ts = _generate_frontend_assets_ts(asset_manifest)
    frontend_scene_contract_ts = _generate_frontend_scene_contract_ts(scene_contract)

    if args.check:
        ok = True
        ok = _check_file(SCENE_CONTRACT_JSON_PATH, scene_contract_json) and ok
        ok = _check_file(FRONTEND_ASSETS_TS_PATH, frontend_assets_ts) and ok
        ok = _check_file(FRONTEND_SCENE_CONTRACT_TS_PATH, frontend_scene_contract_ts) and ok
        if not ok:
            raise SystemExit(
                "Generated editor artifacts are out of date. "
                "Run `python scripts/generate_editor_shared_artifacts.py`.",
            )
        return

    _write(
        SCENE_CONTRACT_JSON_PATH,
        scene_contract_json,
    )
    _write(
        FRONTEND_ASSETS_TS_PATH,
        frontend_assets_ts,
    )
    _write(
        FRONTEND_SCENE_CONTRACT_TS_PATH,
        frontend_scene_contract_ts,
    )


if __name__ == "__main__":
    main()
